#!/usr/bin/env node

const { get } = require("https");

const BASE_API_URL = "https://index.open.mp/server/";

// ruby.nephrite.ro ip addr
const NEPHRITE_ADDRESS = "193.203.39.36:7777";

get(BASE_API_URL + NEPHRITE_ADDRESS, (res) => {
  if (res.statusCode !== 200) {
    return console.log(`Something went wrong: ${res.statusCode}`);
  }

  let output = [];

  res.on("data", (chunk) => {
    output.push(chunk);
  });

  res.on("end", () => {
    output = JSON.parse(Buffer.concat(output).toString());
    console.log(`${output.core.pc}/${output.core.pm}`);
  });
});
