${c1}
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMNmmmmmmNNMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMd````````/NMMMMMMMMMMMMMMMM
MMMMdmMMMMMMMMMMMMMM/      -yymMMMMMMMMMMmdMMMM
MMMN```-:+osyhddmmmo       +mmmddhyso+:-```NMMM
MMMM:`        `````         `````        `:MMMM
MMMMNo/-                               -/oNMMMM
MMNNMd:                                 :dMNNMM
MMd.+hmh/. .-`                   `-. ./hmh+.dMM
MMN`  .+hddh:.                   .:hddh+.  `NMM
MMMh.    .yMNmdys+./       /.+sydmNMy.    .hMMM
MMMMms    `/hNMMMMmh       hmMMMMNh/`    smMMMM
MMMMMd      `-+ydmM+       +Mmdy+-`      dMMMMM
MMMMMm          `oN`       `No`          mMMMMM
MMMMMM/         :No         oN:         /MMMMMM
MMMMMMNs-      .mN.         .Nm-      -sNMMMMMM
MMMMMMMMNh+.` `dMy           yMd` `.+hNMMMMMMMM
MMMMMMMMMMMNh/oNMd+.`     `.+dMNo/hNMMMMMMMMMMM
MMMMMMMMMMMMN/ -odNNh+.`.+hNNdo- /MMMMMMMMMMMMM
MMMMMMMMMMMMy/.   -odNNdNNdo-   ./yMMMMMMMMMMMM
MMMMMMMMMMMM`        -yMy-        `MMMMMMMMMMMM
MMMMMMMMMMMMy/-      `sMs`      -/yMMMMMMMMMMMM
MMMMMMMMMMMMMh/..../leonard/..../hMMMMMMMMMMMMM
MMMMMMMMMMMMMMMNmhs+:.   .:+shmNMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMM+`             `+MMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMNhs/.``   ``./shNMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMNdhyhdNMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
